name: Build UserScript

on:
  push:
    branches:
      - main

jobs:
  build-userscript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build UserScript
        run: |
          echo "Building UserScript..."
          node userscript.js

      - name: Push to repository
        run: |
          echo "Pushing to repository..."
          git config --global user.name "GitHub Action"
          git config --global user.email "45784494+lcandy2@users.noreply.github.com"
          git add Select-like-a-Boss.user.js
          git commit -m "GitHub Action: Keep UserScript up-to-date"
          git push -u origin main